version: '3'
services:
  nginx2:
    container_name: "nginx2"
    build:
      context: ./docker/nginx
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./:/src

  app:
    container_name: "app"
    build:
      context: ./docker/php
    depends_on:
      - mysql
    ports:
      - 5173:5173
    volumes:
      - ./:/src
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql:8.0.28
    command: --max_allowed_packet=32505856
    container_name: "mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
    ports:
      - 3306:3306

  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - 16379:6379